server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-email-service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES}
    queue:
      email:
        name: email.notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true