server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-email-service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    addresses: amqps://auaosgzi:OPbQCwE4q9NQCZgB3-pMJ5CmxyUCkANh@crow.rmq.cloudamqp.com/auaosgzi

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

broker:
  queue:
    email:
      name: email.notification