spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/cafezinho_db
        driver-class-name: org.postgresql.Driver
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}
        jpa:
            hibernate:
                ddl-auto: update
                show-sql: true
            properties:
                hibernate:
                    format_sql: true
            database-platform: org.hibernate.dialect.PostgreSQLDialect
    rabbitmq:
        addresses: ${RABBITMQ_ADDRESSES}
        queues:
            email:
                name: email.notification
            sms:
                name: sms.notification

api:
    security:
        token:
            secret: my-secret-key

cors:
    allowed:
        origins: http://localhost:8080